### ISSUE TITLE
The discord invite link in the readme is broken.

### ISSUE THREAD

**Issue by jejanim** [ElusiveMori/ceres-wc3#25]
The provided link points to the following address: https://discord.com/invite/M4KXP9a
When visiting it, however, discord tells us that the link is no longer valid:

![image](https://user-images.githubusercontent.com/11576006/92513951-6882f480-f211-11ea-9327-13703414e79c.png)

**Comment by Promises** [comment]
he deleted the discord, and his discord account

**Comment by jejanim** [comment]
Fair enough, might want to update the readme though.

**Comment by ElusiveMori** [comment]
The project is discontinued due to the piss-poor state of Reforged and complete lack of any progress in the patches. Sorry.

I'll update the readme.

**Comment by jejanim** [comment]
Thanks for the information @ElusiveMori .
For beginners like me that want to start with editing their maps it is a vital piece information if a project such as this one is discontinued. Maybe this too could be added to the readme?

Thanks, just saw your update 👍

**Comment by ElusiveMori** [comment]
Yeah, I added a notice to the readme. I'll also archive the repository so it's clearly visible that it's inactive. Thanks for bringing it up.
