### ISSUE TITLE
elseif does not allow paranthesis like if does.

### ISSUE THREAD

**Issue by ScrewTheTrees** [ElusiveMori/ceres-wc3#7]
ceres does not seem to be able to parse () if its used in "elseif", as in "if".

This means that: 
>if (group.orderType == Ids.orderTypes.ORDER_GOLDMINE) then
elseif (group.orderType == Ids.orderTypes.ORDER_GOLDMINE) then
end

Will throw an error.
And:

>if (group.orderType == Ids.orderTypes.ORDER_GOLDMINE) then
elseif group.orderType == Ids.orderTypes.ORDER_GOLDMINE then
end

Will run just fine.

the error message is akin to:

> [[31mERROR[0m] -> Could not run map.
[[31mERROR[0m] ->     Cause: Could not build map.
[[31mERROR[0m] ->         Cause: Could not build the script.
[[31mERROR[0m] ->             Cause: Parsing error in xxx\src\AIWorker.lua
[[31mERROR[0m] ->                 Cause:   --> 47:63
   |
47 |     elseif (group.orderType == Ids.orderTypes.ORDER_GOLDMINE) then␍␊
   |                                                               ^---
   |
   = expected StmtReturn, Stmt, Index, MethodCall, or Args

**Comment by ElusiveMori** [comment]
Should have been fixed with the new parser.
